'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("support1")>  _
        Public Property ServerName() As String
            Get
                Return CType(Me("ServerName"),String)
            End Get
            Set
                Me("ServerName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DocsVision45")>  _
        Public Property VirtualFolder() As String
            Get
                Return CType(Me("VirtualFolder"),String)
            End Get
            Set
                Me("VirtualFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Login() As String
            Get
                Return CType(Me("Login"),String)
            End Get
            Set
                Me("Login") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Password() As String
            Get
                Return CType(Me("Password"),String)
            End Get
            Set
                Me("Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8888")>  _
        Public Property Port() As String
            Get
                Return CType(Me("Port"),String)
            End Get
            Set
                Me("Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dv1988")>  _
        Public Property Base() As String
            Get
                Return CType(Me("Base"),String)
            End Get
            Set
                Me("Base") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""UTF-16"" standalone=""no""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<my:Data xmlns:my=""http:"& _ 
            "//www.docsvision.com/schemas/XmlData""><my:CardOrd CardID=""AE73B4AC-1904-4D5E-931"& _ 
            "A-CA23E52363C0"" CardTypeID=""425DD1AC-8DF1-49F0-9A06-FA61381C4FEC"" Description=""T"& _ 
            "estDocument"" CreationDateTime=""2011-10-27T09:53:50"" ChangeDateTime=""2011-10-27T0"& _ 
            "9:55:23"" Template=""0"" Topic=""TestDocument"" xmlns:my=""http://www.docsvision.com/s"& _ 
            "chemas/CardOrd""><my:MainInfo RowID=""59FE06B2-DA00-4180-AB63-B8C359378060"" Name="""& _ 
            "TestDocument"" CreationDate=""2011-10-27T09:53:54.000"" RegistrationDate=""2011-10-2"& _ 
            "7T09:53:54.000"" RegisteredBy=""9037E1CE-9BFE-48E7-81D3-E9DFAEE47819"" Reg_FName=""M"& _ 
            "ihail"" Reg_LName=""Zaharov"" Digest=""Test document for DocsVision Speed Test&#xA;&"& _ 
            "#xA;Filling text:&#xA;&#xA;TestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestT"& _ 
            "estTestTestTestTestTestTestTestTestTestTest"" FilesID=""B6ACFC51-E627-42A5-A520-EB"& _ 
            "4551462BF0"" PropsAsForm=""0""/><my:Properties><my:PropertiesRow RowID=""0DD1CB8B-EC"& _ 
            "24-44FE-9DF1-0A74DBAC23EF"" Name=""Property1"" WriteToCard=""1"" Order=""1"" ParamType="& _ 
            """0"" DisplayValue=""""/><my:PropertiesRow RowID=""671D68B7-8B7A-4723-9020-1642F8CC02"& _ 
            "9A"" Name=""Property2"" WriteToCard=""1"" Order=""2"" ParamType=""1"" DisplayValue=""""/></"& _ 
            "my:Properties></my:CardOrd></my:Data>")>  _
        Public Property CardXML() As String
            Get
                Return CType(Me("CardXML"),String)
            End Get
            Set
                Me("CardXML") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.DocsVisionSpeedTest.My.MySettings
            Get
                Return Global.DocsVisionSpeedTest.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
